# @Author: shifath.nafis
# @Date:   2024-03-28 03:15:18
# @Last Modified by:   shifath.nafis
# @Last Modified time: 2024-03-29 18:09:14
exclude: '^tests/snapshots/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    -   id: ruff
-   repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    - id: prettier
      types_or: [css, javascript, ts, tsx, html]
